{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minicrm.postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minicrm.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  selector:
    {{- include "minicrm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  clusterIP: None  # Headless service for StatefulSet
{{- end }}
